/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javierbarciela.proyectofin.views;

import com.javierbarciela.proyectofin.modelo.Usuario;
import com.javierbarciela.proyectofin.service.ProyectoFinService;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author daw1
 */
public class Login extends javax.swing.JFrame {

    private ProyectoFinService service = new ProyectoFinService();
    
    public Login() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        pnlLogExit = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlRegistrarse = new javax.swing.JPanel();
        btnRegistrarse = new javax.swing.JButton();
        pnlInfo = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        pnlError = new javax.swing.JPanel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitulo.setText("Login");
        pnlTitulo.add(lblTitulo);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlBotones.setLayout(new java.awt.BorderLayout());

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        pnlLogExit.add(btnEntrar);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlLogExit.add(btnSalir);

        pnlBotones.add(pnlLogExit, java.awt.BorderLayout.PAGE_START);

        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        pnlRegistrarse.add(btnRegistrarse);

        pnlBotones.add(pnlRegistrarse, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlInfo.setLayout(new java.awt.BorderLayout());

        pnlDatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlDatos.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuario");
        pnlDatos.add(lblUsuario);

        txtUsuario.setText("juantxu");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlDatos.add(txtUsuario);

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Contraseña");
        pnlDatos.add(lblPassword);

        pwdPassword.setText("patata");
        pnlDatos.add(pwdPassword);

        pnlInfo.add(pnlDatos, java.awt.BorderLayout.CENTER);

        lblError.setText(" ");
        pnlError.add(lblError);

        pnlInfo.add(pnlError, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlInfo, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 279));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        login();
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        new Registro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarseActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IconFontSwing.register(FontAwesome.getIconFont());
                new Login().setVisible(true);
            }
        });
    }

    private void login(){
        Usuario u = null;
        if (txtUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "Debe especificarse el usuario",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            txtUsuario.requestFocus();
        } else if (pwdPassword.getPassword().length == 0){
            JOptionPane.showMessageDialog(this, 
                "Debe especificarse la contraseña",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            pwdPassword.requestFocus();
        } else {
            String pwd = new String(pwdPassword.getPassword());
            u = service.login(txtUsuario.getText(), pwd);
            if (u == null){
                lblError.setText("Usuario o contraseña erróneos");
                pwdPassword.setText("");
                pwdPassword.requestFocus();
            } else {
                new Principal(u).setVisible(true);
                this.dispose();
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlError;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlLogExit;
    private javax.swing.JPanel pnlRegistrarse;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
