/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javierbarciela.proyectofin.views;

import com.javierbarciela.proyectofin.dao.CategoriaBBDD;
import com.javierbarciela.proyectofin.dao.ProductoBBDD;
import com.javierbarciela.proyectofin.modelo.Categoria;
import com.javierbarciela.proyectofin.modelo.Producto;
import com.javierbarciela.proyectofin.modelo.Usuario;
import com.javierbarciela.proyectofin.service.ProyectoFinService;
import com.javierbarciela.proyectofin.util.Foto;
import com.javierbarciela.proyectofin.util.OrdenarCategoriasPorNombre;
import com.javierbarciela.proyectofin.util.OrdenarProductosPorNombre;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author daw1
 */
public class MisProductos extends javax.swing.JFrame {

    public static final int ALTA = 1;
    public static final int MODIFICACION = 2;
    public static final int CONSULTA = 3;
    
    private ProyectoFinService service = new ProyectoFinService();
    private Foto foto = new Foto();
    
    private Usuario usuario;
    
    private List<Producto> productos = new ArrayList<>();
    private List<Categoria> categorias = new ArrayList<>();
    
    private int estado;
    private int pos = 1;
    
    private File f;
    
    public MisProductos(Usuario u) {
        initComponents();
        this.usuario = u;
        if(service.poseeProductos(this.usuario.getIdUsuario())){
            estado = CONSULTA;
            mostrar();
        } else {
            estado = ALTA;
        }
        categorias = service.getCategorias();
        Collections.sort(categorias, new OrdenarCategoriasPorNombre());
        cargarCombos();
        actualizarEstado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlBotonesRecorrer = new javax.swing.JPanel();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        lblNumProducto = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();
        pnlBotonesActuar = new javax.swing.JPanel();
        pnlGuardar = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        pnlEliminar = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        pnlEstados = new javax.swing.JPanel();
        btnAlta = new javax.swing.JButton();
        btnModificacion = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        pnlBuscar = new javax.swing.JPanel();
        txtNombreProducto = new javax.swing.JTextField();
        cbxProductos = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        pnlInfo = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        lblFechaAlta = new javax.swing.JLabel();
        lblValoracion = new javax.swing.JLabel();
        jsValoracion = new javax.swing.JSlider();
        lblCategoria = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblPrecio = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblFotoCategoria = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        ftxFechaAlta = new javax.swing.JFormattedTextField();
        ftxPrecio = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAlta = new javax.swing.JMenuItem();
        menuModificacion = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPrimero = new javax.swing.JMenuItem();
        menuAnterior = new javax.swing.JMenuItem();
        menuSiguiente = new javax.swing.JMenuItem();
        menuUltimo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuGuardar = new javax.swing.JMenuItem();
        menuEliminar = new javax.swing.JMenuItem();
        menuCancelar = new javax.swing.JMenuItem();
        menuVolver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Mis productos");
        pnlTitulo.add(lblTitulo);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        btnPrimero.setText("Primero");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        pnlBotonesRecorrer.add(btnPrimero);

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        pnlBotonesRecorrer.add(btnAnterior);
        pnlBotonesRecorrer.add(lblNumProducto);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        pnlBotonesRecorrer.add(btnSiguiente);

        btnUltimo.setText("Último");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        pnlBotonesRecorrer.add(btnUltimo);

        getContentPane().add(pnlBotonesRecorrer, java.awt.BorderLayout.PAGE_END);

        pnlContenido.setLayout(new java.awt.BorderLayout());

        pnlBotonesActuar.setLayout(new java.awt.BorderLayout());

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlGuardar.add(btnGuardar);

        pnlBotonesActuar.add(pnlGuardar, java.awt.BorderLayout.PAGE_START);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlEliminar.add(btnEliminar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlEliminar.add(btnCancelar);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlEliminar.add(btnVolver);

        pnlBotonesActuar.add(pnlEliminar, java.awt.BorderLayout.CENTER);

        pnlContenido.add(pnlBotonesActuar, java.awt.BorderLayout.PAGE_END);

        pnlEstados.setLayout(new java.awt.GridLayout(3, 1));

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        pnlEstados.add(btnAlta);

        btnModificacion.setText("Modificación");
        btnModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificacionActionPerformed(evt);
            }
        });
        pnlEstados.add(btnModificacion);

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        pnlEstados.add(btnConsulta);

        pnlContenido.add(pnlEstados, java.awt.BorderLayout.LINE_END);

        pnlDatos.setLayout(new java.awt.BorderLayout());

        txtNombreProducto.setText("NuevoProducto");
        pnlBuscar.add(txtNombreProducto);

        pnlBuscar.add(cbxProductos);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlBuscar.add(btnBuscar);

        pnlDatos.add(pnlBuscar, java.awt.BorderLayout.PAGE_START);

        pnlInfo.setLayout(new java.awt.GridBagLayout());

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFotoMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.2;
        pnlInfo.add(lblFoto, gridBagConstraints);

        txaDescripcion.setColumns(20);
        txaDescripcion.setRows(10);
        txaDescripcion.setTabSize(10);
        txaDescripcion.setAutoscrolls(false);
        jScrollPane1.setViewportView(txaDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.6;
        pnlInfo.add(jScrollPane1, gridBagConstraints);

        lblFechaAlta.setText("Fecha Alta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        pnlInfo.add(lblFechaAlta, gridBagConstraints);

        lblValoracion.setText("Valoración");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        pnlInfo.add(lblValoracion, gridBagConstraints);

        jsValoracion.setMajorTickSpacing(1);
        jsValoracion.setMaximum(5);
        jsValoracion.setMinimum(1);
        jsValoracion.setPaintLabels(true);
        jsValoracion.setPaintTicks(true);
        jsValoracion.setValue(3);
        jsValoracion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlInfo.add(jsValoracion, gridBagConstraints);

        lblCategoria.setText("Categoría");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        pnlInfo.add(lblCategoria, gridBagConstraints);

        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlInfo.add(cbxCategoria, gridBagConstraints);

        lblPrecio.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        pnlInfo.add(lblPrecio, gridBagConstraints);

        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStock.setText("Stock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        pnlInfo.add(lblStock, gridBagConstraints);

        lblFotoCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoCategoria.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlInfo.add(lblFotoCategoria, gridBagConstraints);

        txtCantidad.setText("00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 0.1;
        pnlInfo.add(txtCantidad, gridBagConstraints);

        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCantidad.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlInfo.add(lblCantidad, gridBagConstraints);

        ftxFechaAlta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlInfo.add(ftxFechaAlta, gridBagConstraints);

        ftxPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlInfo.add(ftxPrecio, gridBagConstraints);

        pnlDatos.add(pnlInfo, java.awt.BorderLayout.CENTER);

        pnlContenido.add(pnlDatos, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlContenido, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Modo");

        menuAlta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuAlta.setText("Alta");
        menuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAltaActionPerformed(evt);
            }
        });
        jMenu1.add(menuAlta);

        menuModificacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuModificacion.setText("Modificación");
        menuModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModificacionActionPerformed(evt);
            }
        });
        jMenu1.add(menuModificacion);

        menuConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuConsulta.setText("Consulta");
        menuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(menuConsulta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Recorrer");

        menuPrimero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_UP, 0));
        menuPrimero.setText("Primero");
        menuPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrimeroActionPerformed(evt);
            }
        });
        jMenu2.add(menuPrimero);

        menuAnterior.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, 0));
        menuAnterior.setText("Anterior");
        jMenu2.add(menuAnterior);

        menuSiguiente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, 0));
        menuSiguiente.setText("Siguiente");
        menuSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSiguienteActionPerformed(evt);
            }
        });
        jMenu2.add(menuSiguiente);

        menuUltimo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DOWN, 0));
        menuUltimo.setText("Último");
        menuUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUltimoActionPerformed(evt);
            }
        });
        jMenu2.add(menuUltimo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Acción");

        menuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menuGuardar.setText("Guardar");
        menuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarActionPerformed(evt);
            }
        });
        jMenu3.add(menuGuardar);

        menuEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuEliminar.setText("Eliminar");
        menuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarActionPerformed(evt);
            }
        });
        jMenu3.add(menuEliminar);

        menuCancelar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCancelar.setText("Cancelar");
        menuCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelarActionPerformed(evt);
            }
        });
        jMenu3.add(menuCancelar);

        menuVolver.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuVolver.setText("Volver");
        menuVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVolverActionPerformed(evt);
            }
        });
        jMenu3.add(menuVolver);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(748, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (enConsulta()) {   
            if (pos != productos.size()){
                pos++;
            }
            cambiarDeProducto(pos-1);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (enConsulta()) {
            if (pos != 1){
                pos--;
            }
            cambiarDeProducto(pos-1);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        if (enConsulta()) {
            pos = productos.size();
            cambiarDeProducto(pos-1);
        }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        if (enConsulta()) {
            pos = 1;
            cambiarDeProducto(pos-1);
        }
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        cbxCategoria.getSelectedItem();//esto qué hace exactamente¿?¿?¿?
        
        ImageIcon imIc = foto.establecerFotoCategoria( (Categoria) cbxCategoria.getSelectedItem());
        lblFotoCategoria.setIcon(imIc);
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (enConsulta()) {
            Producto p = (Producto) cbxProductos.getSelectedItem();
            int i;
            for(i=0;i<productos.size()&&productos.get(i).getIdProducto()!=p.getIdProducto();i++);
            cambiarDeProducto(i);
            pos = i+1;
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        if (enConsulta()){
            estado = ALTA;
            actualizarEstado();
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificacionActionPerformed
        if (enConsulta()){
            estado = MODIFICACION;
            actualizarEstado();
        }
    }//GEN-LAST:event_btnModificacionActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        if (!productos.isEmpty()){
            estado = CONSULTA;
            actualizarEstado();
        } else {
            JOptionPane.showMessageDialog(null,
                    "No hay productos que consultar.", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new Principal(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void lblFotoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMousePressed
        JFileChooser jfc = new JFileChooser();
        jfc.setMultiSelectionEnabled(false);
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileFilter filter = new FileNameExtensionFilter("JPEG (*.jpeg,*.jpg)", "jpg", "jpeg");
        jfc.addChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("PNG (*.png)", "png");
        jfc.addChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("GIF (*.gif)", "gif");
        jfc.addChoosableFileFilter(filter);
        filter = new FileNameExtensionFilter("Todas las imágenes", "gif","png","jpg","jpeg","bmp");
        jfc.addChoosableFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false);
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            f = jfc.getSelectedFile();
            File fd = new File("images", f.getName());
            try {
                BufferedInputStream bis = new BufferedInputStream(
                        new FileInputStream(f));
                BufferedOutputStream bos = new BufferedOutputStream(
                        new FileOutputStream(fd));
                if (!f.equals(fd)){
                    int c;
                while ((c = bis.read()) != -1) {
                    bos.write(c);
                }
                bos.flush();
                bos.close();
                bis.close();
                ImageIcon imIc = new ImageIcon("images/" + f.getName());
                Image imag = imIc.getImage();
                int max = Math.max(imIc.getIconWidth(), imIc.getIconHeight());
                double fe = 150.0 / max;
                imag = imag.getScaledInstance(
                        (int) (imIc.getIconWidth() * fe),
                        (int) (imIc.getIconHeight() * fe), Image.SCALE_SMOOTH);
                imIc.setImage(imag);
                lblFoto.setIcon(imIc);  
                f = fd;
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MisProductos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MisProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblFotoMousePressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (estado == MODIFICACION) {
            guardarModificacion();
            estado = CONSULTA;
            actualizarEstado();
        } else if (estado == ALTA){
            if (!comprobarCamposVacios()){
                crearProducto();
                estado = CONSULTA;
                actualizarEstado();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (enConsulta()) {
            eliminarProducto();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void menuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaActionPerformed
        if (!productos.isEmpty()){
            estado = CONSULTA;
            actualizarEstado();
        } else {
            JOptionPane.showMessageDialog(null,
                    "No hay productos que consultar.", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuConsultaActionPerformed

    private void menuPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrimeroActionPerformed
        if (enConsulta()) {
            pos = 1;
            cambiarDeProducto(pos-1);
        }
    }//GEN-LAST:event_menuPrimeroActionPerformed

    private void menuVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVolverActionPerformed
        new Principal(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuVolverActionPerformed

    private void menuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAltaActionPerformed
        if (enConsulta()){
            estado = ALTA;
            actualizarEstado();
        }
    }//GEN-LAST:event_menuAltaActionPerformed

    private void menuModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModificacionActionPerformed
        if (enConsulta()){
            estado = MODIFICACION;
            actualizarEstado();
        }
    }//GEN-LAST:event_menuModificacionActionPerformed

    private void menuUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUltimoActionPerformed
        if (enConsulta()) {
            pos = productos.size();
            cambiarDeProducto(pos-1);
        }
    }//GEN-LAST:event_menuUltimoActionPerformed

    private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarActionPerformed
        if (enConsulta()) {
            eliminarProducto();
        }
    }//GEN-LAST:event_menuEliminarActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        if (estado == MODIFICACION) {
            guardarModificacion();
            estado = CONSULTA;
            actualizarEstado();
        } else if (estado == ALTA){
            if (!comprobarCamposVacios()){
                crearProducto();
                estado = CONSULTA;
                actualizarEstado();
            }
        }
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void menuSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSiguienteActionPerformed
        if (enConsulta()) {   
            if (pos != productos.size()){
                pos++;
            }
            cambiarDeProducto(pos-1);
        }
    }//GEN-LAST:event_menuSiguienteActionPerformed

    private void menuCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelarActionPerformed
        if(!enConsulta()){
            estado = CONSULTA;
            actualizarEstado();
        }
    }//GEN-LAST:event_menuCancelarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if(!enConsulta()){
            estado = CONSULTA;
            actualizarEstado();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

     
    
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisProductos().setVisible(true);
            }
        });
    }*/
    
    private void mostrar(){
        productos = service.getProductosUsuario(this.usuario);
        Collections.sort(productos, new OrdenarProductosPorNombre());
        System.out.println("\nSorted by nombre");
        for (int i=0; i<productos.size(); i++) // imprimir arraylist
            System.out.println(productos.get(i).getNombre());
        lblNumProducto.setText(pos + "/" + productos.size());
        cambiarDeProducto(pos-1);
        ftxPrecio.setValue(productos.get(pos-1).getPrecio());
    }
    
    private boolean enConsulta(){
        if (estado == CONSULTA){
            return true;
        } else {
            return false;
        }
    }
    
    private void actualizarEstado(){
        switch (estado){
            case ALTA:
                establecerAlta();
                break;
            case MODIFICACION:
                establecerModificacion();
                break;
            case CONSULTA:
                establecerConsulta();
                break;
        }
    }
    
    private void cambiarDeProducto(int pos){ //A ESTE MÉTODO YA LE ENTRA LA POS-1
        txtNombreProducto.setText(productos.get(pos).getNombre());
        lblNumProducto.setText((pos+1) + "/" + productos.size());
        txaDescripcion.setText(productos.get(pos).getDescripcion());
        ftxFechaAlta.setValue(productos.get(pos).getFechaAlta());
        cambiarFotoProducto(pos); //A ESTE MÉTODO YA LE ENTRA LA POS-1
        /*cambiarFotoCategoria(productos.get(pos).getCategoria());*/
        jsValoracion.setValue(productos.get(pos).getValoracion());
        setComboBox(pos);
        ftxPrecio.setValue(productos.get(pos).getPrecio());
        cambiarStock(pos);
    }
    
    private void setComboBox(int pos){
        int idCategoria = productos.get(pos).getCategoria();
        Categoria c = service.getCategoria(idCategoria);
        cbxCategoria.setSelectedItem(c);
    }
    
    private void cambiarFotoProducto(int pos){
        ImageIcon imIc = new ImageIcon(productos.get(pos).getImagen());
        Image image = imIc.getImage();
        int max = (int) Math.max(imIc.getIconWidth(), imIc.getIconHeight());
        double factorEscala = 150.0/max;
        int ancho = (int) (imIc.getIconWidth() * factorEscala);
        int alto = (int) (imIc.getIconHeight() * factorEscala);
        image = image.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        imIc.setImage(image);
        lblFoto.setIcon(imIc);
    }
    /*
    private void cambiarFotoCategoria(int idCategoria){
        Categoria c = service.getCategoria(idCategoria);
        ImageIcon imIc = new ImageIcon(c.getImagen());
        Image image = imIc.getImage();
        int max = (int) Math.max(imIc.getIconWidth(), imIc.getIconHeight());
        double factorEscala = 50.0/max;
        int ancho = (int) (imIc.getIconWidth() * factorEscala);
        int alto = (int) (imIc.getIconHeight() * factorEscala);
        image = image.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        imIc.setImage(image);
        lblFotoCategoria.setIcon(imIc);
    }*/
    
    private void cambiarStock(int pos){
        if(productos.get(pos).getCantidad() > 0){
            lblStock.setText("En stock.");
        } else {
            lblStock.setText("Fuera de stock.");
        }
    }
    
    private void cargarCombos() {
        
        for (Producto p : productos) {
            cbxProductos.addItem(p);
        }
        if (!productos.isEmpty()){
            cbxProductos.setSelectedIndex(0);
        }
        
        for (Categoria c : categorias) {
            cbxCategoria.addItem(c);
        }
        if (!productos.isEmpty()) {
            int idCategoria = productos.get(pos-1).getCategoria();
            cbxCategoria.setSelectedItem(service.getCategoria(idCategoria));
        } else {
            cbxCategoria.setSelectedIndex(0);
        }
    }
    
    private void eliminarProducto(){
        Producto p = productos.get(pos-1);
        cbxProductos.removeItem(p);
        service.eliminarProducto(p);
        mostrar();
        
    }
    
    private void establecerAlta(){
        
        resetearCampos();
        
        btnAlta.setBackground(Color.BLACK);
        btnAlta.setForeground(Color.WHITE);
        btnModificacion.setBackground(Color.WHITE);
        btnModificacion.setForeground(Color.BLACK);
        btnConsulta.setBackground(Color.WHITE);
        btnConsulta.setForeground(Color.BLACK);
        
        btnCancelar.setBackground(Color.YELLOW);
        btnEliminar.setBackground(Color.GRAY);
        btnEliminar.setForeground(Color.BLACK);
        btnGuardar.setBackground(Color.GREEN);
        btnGuardar.setForeground(Color.BLACK);
        
        btnPrimero.setBackground(Color.GRAY);
        btnAnterior.setBackground(Color.GRAY);
        btnSiguiente.setBackground(Color.GRAY);
        btnUltimo.setBackground(Color.GRAY);
        
        btnModificacion.setBackground(Color.GRAY);
    }
    
    private void resetearCampos(){
        txtNombreProducto.setEditable(true);
        txtNombreProducto.setText("Nuevo Producto");
        ImageIcon imIc = foto.establecerFotoFactor("images/notfound.png", 150.0);
        lblFoto.setIcon(imIc);
        txaDescripcion.setText("");
        txaDescripcion.setEditable(true);
        Date date = new Date();
        ftxFechaAlta.setValue(date);
        /*ftxFechaAlta.setEditable(false);*/ //se accede desde consulta, donde ya no ses editable
        jsValoracion.setValue(3);
        cbxCategoria.setSelectedIndex(0);        
        cbxCategoria.setEnabled(true);
        ftxPrecio.setValue(0);
        ftxPrecio.setEditable(true);
        lblNumProducto.setText("Nuevo");
        txtNombreProducto.setVisible(true);
        txtNombreProducto.revalidate();
        txtNombreProducto.repaint();
        //txtNombreProducto.setText("");
        txtNombreProducto.setEditable(true);
        txtCantidad.setVisible(true);
        txtCantidad.revalidate();
        txtCantidad.repaint();
        //txtCantidad.setText("");
        txtCantidad.setEditable(true);
        lblStock.setText("");
        
    }
    
    private void crearProducto(){
        Producto p = new Producto();
        List<Producto> todosProductos = new ArrayList<>();
        todosProductos = service.getProductos();
        p.setIdProducto(buscarMayorInt(todosProductos)+1);
        p.setIdUsuario(this.usuario.getIdUsuario());
        p.setNombre(txtNombreProducto.getText());
        p.setDescripcion(txaDescripcion.getText());
        p.setValoracion(jsValoracion.getValue());
        Categoria c = (Categoria) cbxCategoria.getSelectedItem();
        p.setCategoria(c.getIdCategoria());
        p.setPrecio(Double.parseDouble(String.valueOf(ftxPrecio.getValue())));
        if (f != null) {
            try {
                p.setImagen(f.getCanonicalPath());
            } catch (IOException ex) {
                Logger.getLogger(MisProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            p.setImagen("images/notfound.png");
        }
        p.setFechaAlta( (Date) ftxFechaAlta.getValue());
        p.setCantidad(Integer.parseInt(txtCantidad.getText()));
        service.nuevoProducto(p);
        productos = service.getProductosUsuario(this.usuario);
        Collections.sort(productos, new OrdenarProductosPorNombre());
        /*int i;
        for(i=0;i<productos.size() 
                && productos.get(i).getIdProducto() != p.getIdProducto();i++); //NO ENCUENTRA EL PRODUCTO y no sé dónde lo pone
        pos = i;*/
        pos = 1;
        mostrar();
        cargarCombos();
    }
    
    private boolean comprobarCamposVacios(){
        if (txtNombreProducto.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "Debe especificarse el nombre del producto",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            txtNombreProducto.requestFocus();
            return true;
        } else if (txaDescripcion.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "Debe especificarse la descripción",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            txaDescripcion.requestFocus();
            return true;
        } else if (ftxPrecio.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "Debe especificarse el precio",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            ftxPrecio.requestFocus();
            return true;
        } else if (txtCantidad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "Debe especificarse la cantidad",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            txtCantidad.requestFocus();
            return true;
        } else {
            return false;
        }
    }
    
    private int buscarMayorInt(List<Producto> lista){
        int mayor = -1;
        for (int i=0; i<lista.size(); i++){
            if (lista.get(i).getIdProducto() > mayor){
                mayor = lista.get(i).getIdProducto();
            }
        }
        return mayor;
    }
    
    private void establecerModificacion(){
        mostrar();
        
        txtNombreProducto.setEditable(true);
        txtNombreProducto.setVisible(true);
        txtNombreProducto.revalidate();
        txtNombreProducto.repaint();
        txtNombreProducto.setText(productos.get(pos-1).getNombre());
        txtNombreProducto.setEditable(true);
        txtCantidad.setVisible(true);
        txtCantidad.revalidate();
        txtCantidad.repaint();
        txtCantidad.setText(String.valueOf(productos.get(pos-1).getCantidad()));
        txtCantidad.setEditable(true);
        txaDescripcion.setEditable(true);
        /*ftxFechaAlta.setEditable(true);*/ //se accede desde consulta, donde no es editable
        cbxCategoria.setEnabled(true);
        ftxPrecio.setEditable(true);
        
        btnModificacion.setBackground(Color.BLACK);
        btnModificacion.setForeground(Color.WHITE);
        btnAlta.setBackground(Color.WHITE);
        btnAlta.setForeground(Color.BLACK);
        btnConsulta.setBackground(Color.WHITE);
        btnConsulta.setForeground(Color.BLACK);
        
        btnCancelar.setBackground(Color.YELLOW);
        btnEliminar.setBackground(Color.GRAY);
        btnEliminar.setForeground(Color.BLACK);
        btnGuardar.setBackground(Color.GREEN);
        btnGuardar.setForeground(Color.BLACK);
        
        btnPrimero.setBackground(Color.GRAY);
        btnAnterior.setBackground(Color.GRAY);
        btnSiguiente.setBackground(Color.GRAY);
        btnUltimo.setBackground(Color.GRAY);
        
        btnAlta.setBackground(Color.GRAY);
    }
    
    private void guardarModificacion(){
        Producto p = new Producto();
        p.setIdProducto(productos.get(pos-1).getIdProducto());
        p.setIdUsuario(productos.get(pos-1).getIdUsuario());
        p.setNombre(txtNombreProducto.getText());
        p.setDescripcion(txaDescripcion.getText());
        p.setValoracion(jsValoracion.getValue());
        Categoria c = (Categoria) cbxCategoria.getSelectedItem();
        p.setCategoria(c.getIdCategoria());
        p.setPrecio((double) ftxPrecio.getValue());
        if (f != null) {
            try {
                p.setImagen(f.getCanonicalPath());
            } catch (IOException ex) {
                Logger.getLogger(MisProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            p.setImagen("images/notfound.png");
        }
        p.setFechaAlta( (Date) ftxFechaAlta.getValue());
        p.setCantidad(Integer.parseInt(txtCantidad.getText()));
        service.modificarProducto(p);
        productos = service.getProductosUsuario(this.usuario);
        Collections.sort(productos, new OrdenarProductosPorNombre());
        /*int i;
        for(i=0;i<productos.size() 
                && productos.get(i).getIdProducto() != p.getIdProducto();i++);
        pos = i;*/
        pos = 1;
        mostrar();
    }
    
    private void establecerConsulta(){
        mostrar();
        
        txtNombreProducto.setEditable(false);
        txtNombreProducto.setVisible(true);
        txtNombreProducto.revalidate();
        txtNombreProducto.repaint();
        txaDescripcion.setEditable(false);
        ftxFechaAlta.setEditable(false);
        //jsValoracion.setEditable(false);//no deja, no hacer que en modificación cambie?????
        cbxCategoria.setEnabled(false);
        ftxPrecio.setEditable(false);
        txtCantidad.setVisible(false);
        
        btnConsulta.setBackground(Color.BLACK);
        btnConsulta.setForeground(Color.WHITE);
        btnAlta.setBackground(Color.WHITE);
        btnAlta.setForeground(Color.BLACK);
        btnModificacion.setBackground(Color.WHITE);
        btnModificacion.setForeground(Color.BLACK);
        
        btnCancelar.setBackground(Color.GRAY);
        btnEliminar.setBackground(Color.RED);
        btnEliminar.setForeground(Color.WHITE);
        btnGuardar.setBackground(Color.GRAY);
        btnGuardar.setForeground(Color.BLACK);
        
        btnVolver.setBackground(Color.LIGHT_GRAY);
        
        btnPrimero.setBackground(Color.LIGHT_GRAY);
        btnAnterior.setBackground(Color.LIGHT_GRAY);
        btnSiguiente.setBackground(Color.LIGHT_GRAY);
        btnUltimo.setBackground(Color.LIGHT_GRAY);
        
        btnAlta.setBackground(Color.WHITE);
        btnModificacion.setBackground(Color.WHITE);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificacion;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Categoria> cbxCategoria;
    private javax.swing.JComboBox<Producto> cbxProductos;
    private javax.swing.JFormattedTextField ftxFechaAlta;
    private javax.swing.JFormattedTextField ftxPrecio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jsValoracion;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblFechaAlta;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblFotoCategoria;
    private javax.swing.JLabel lblNumProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValoracion;
    private javax.swing.JMenuItem menuAlta;
    private javax.swing.JMenuItem menuAnterior;
    private javax.swing.JMenuItem menuCancelar;
    private javax.swing.JMenuItem menuConsulta;
    private javax.swing.JMenuItem menuEliminar;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuModificacion;
    private javax.swing.JMenuItem menuPrimero;
    private javax.swing.JMenuItem menuSiguiente;
    private javax.swing.JMenuItem menuUltimo;
    private javax.swing.JMenuItem menuVolver;
    private javax.swing.JPanel pnlBotonesActuar;
    private javax.swing.JPanel pnlBotonesRecorrer;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlEliminar;
    private javax.swing.JPanel pnlEstados;
    private javax.swing.JPanel pnlGuardar;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
