/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javierbarciela.proyectofin.views;

import com.javierbarciela.proyectofin.modelo.Producto;
import com.javierbarciela.proyectofin.modelo.Usuario;
import com.javierbarciela.proyectofin.service.ProyectoFinService;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author daw1
 */
public class Principal extends javax.swing.JFrame {
    
    private Usuario usuario;
    private ProyectoFinService service = new ProyectoFinService();
    
    public Principal(Usuario u) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.usuario = u;
        lblNickname.setText(this.usuario.getUsuario());
        ImageIcon imIc = new ImageIcon(u.getFoto());
        Image image = imIc.getImage();
        image = image.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        imIc.setImage(image);
        lblFoto.setIcon(imIc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlImagen = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        pnlSalir = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        pnlInterfaz = new javax.swing.JPanel();
        pnlCuenta = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        lblFoto = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        lblNickname = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnLogOut = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        pnlOpciones = new javax.swing.JPanel();
        btnMisProductos = new javax.swing.JButton();
        btnVerProductosVenta = new javax.swing.JButton();
        btnProductosComprados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImagen.setText("Aitazon");
        pnlImagen.add(lblImagen);

        getContentPane().add(pnlImagen, java.awt.BorderLayout.PAGE_START);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlSalir.add(btnSalir);

        getContentPane().add(pnlSalir, java.awt.BorderLayout.PAGE_END);

        pnlInterfaz.setLayout(new java.awt.BorderLayout());

        pnlCuenta.setLayout(new javax.swing.BoxLayout(pnlCuenta, javax.swing.BoxLayout.LINE_AXIS));
        pnlCuenta.add(filler5);

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlCuenta.add(lblFoto);
        pnlCuenta.add(filler4);

        lblNickname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNickname.setText(" ");
        pnlCuenta.add(lblNickname);
        pnlCuenta.add(filler2);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnlCuenta.add(btnLogOut);
        pnlCuenta.add(filler6);

        pnlInterfaz.add(pnlCuenta, java.awt.BorderLayout.PAGE_START);

        pnlOpciones.setLayout(new java.awt.GridLayout(3, 1));

        btnMisProductos.setText("Mis productos");
        btnMisProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisProductosActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnMisProductos);

        btnVerProductosVenta.setText("Ver Productos En Venta");
        btnVerProductosVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProductosVentaActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnVerProductosVenta);

        btnProductosComprados.setText("Productos Comprados");
        pnlOpciones.add(btnProductosComprados);

        pnlInterfaz.add(pnlOpciones, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlInterfaz, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(608, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnMisProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisProductosActionPerformed
        new MisProductos(this.usuario).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnMisProductosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVerProductosVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProductosVentaActionPerformed
        new VerProductosEnVenta(this.usuario).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVerProductosVentaActionPerformed

    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMisProductos;
    private javax.swing.JButton btnProductosComprados;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerProductosVenta;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JPanel pnlCuenta;
    private javax.swing.JPanel pnlImagen;
    private javax.swing.JPanel pnlInterfaz;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlSalir;
    // End of variables declaration//GEN-END:variables
}
