/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javierbarciela.proyectofin.views;

import com.javierbarciela.proyectofin.modelo.Usuario;
import com.javierbarciela.proyectofin.service.ProyectoFinService;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author daw1
 */
public class Registro extends javax.swing.JFrame {

    private ProyectoFinService service = new ProyectoFinService();
    
    public Registro() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlInfo = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        lblNombrePila = new javax.swing.JLabel();
        txtNombrePila = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        lblRepetirPassword = new javax.swing.JLabel();
        pwdRepetirPassword = new javax.swing.JPasswordField();
        pnlError = new javax.swing.JPanel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Registro");
        pnlTitulo.add(lblTitulo);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnConfirmar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlInfo.setLayout(new java.awt.BorderLayout());

        pnlDatos.setLayout(new java.awt.GridLayout(5, 2, 10, 10));

        lblNombrePila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombrePila.setText("Nombre de pila");
        pnlDatos.add(lblNombrePila);

        txtNombrePila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePilaActionPerformed(evt);
            }
        });
        pnlDatos.add(txtNombrePila);

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email");
        pnlDatos.add(lblEmail);
        pnlDatos.add(txtEmail);

        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreUsuario.setText("Nombre de usuario");
        pnlDatos.add(lblNombreUsuario);
        pnlDatos.add(txtNombreUsuario);

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Contraseña");
        pnlDatos.add(lblPassword);

        pwdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPasswordActionPerformed(evt);
            }
        });
        pnlDatos.add(pwdPassword);

        lblRepetirPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRepetirPassword.setText("Repetir Contraseña");
        pnlDatos.add(lblRepetirPassword);
        pnlDatos.add(pwdRepetirPassword);

        pnlInfo.add(pnlDatos, java.awt.BorderLayout.PAGE_START);

        lblError.setText(" ");
        pnlError.add(lblError);

        pnlInfo.add(pnlError, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlInfo, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        registrarse();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtNombrePilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePilaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void pwdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    private void registrarse(){
        if (txtNombrePila.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "Debe especificarse el nombre de pila",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            txtNombrePila.requestFocus();
        } else if (txtEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "Debe especificarse el email",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
        } else if (txtEmail.getText().indexOf("@") == -1){  // Aquí comprueba que hay una arroba, para saber que
            JOptionPane.showMessageDialog(this,             // es un email
                "El dato introducido no es un email",
                "Dato no válido",
                JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
        } else if (txtNombreUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "Debe especificarse el nombre de usuario",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            txtNombreUsuario.requestFocus();
        } else if (txtNombreUsuario.getText().indexOf("@") != -1){  // Aquí comprueba que no hay arroba para no
            JOptionPane.showMessageDialog(this,                     // confundirlo con el email
                "Ha introducido un carácter no válido en el campo de nombre de usuario",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            txtNombreUsuario.requestFocus();
        } else if (pwdPassword.getPassword().length == 0){
            JOptionPane.showMessageDialog(this, 
                "Debe especificarse la contraseña",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            pwdPassword.requestFocus();
        } else if (pwdRepetirPassword.getPassword().length == 0){
            JOptionPane.showMessageDialog(this, 
                "Debe repetir la contraseña",
                "Faltan datos",
                JOptionPane.ERROR_MESSAGE);
            pwdRepetirPassword.requestFocus();
        } else if (!new String(pwdPassword.getPassword()).equals(new String(pwdRepetirPassword.getPassword()))){
            lblError.setText("Las contraseñas no coinciden");
        } else {
            lblError.setText("");
            String nombrePila = new String(txtNombrePila.getText());
            String email = new String(txtEmail.getText());
            String nombreUsuario = new String(txtNombreUsuario.getText());
            String pwd = new String(pwdPassword.getPassword());
            service.registrarse(nombrePila, email, nombreUsuario, pwd);
            new Login().setVisible(true);
            this.dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblNombrePila;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRepetirPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlError;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JPasswordField pwdRepetirPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombrePila;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
