/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javierbarciela.proyectofin.views;

import com.javierbarciela.proyectofin.modelo.Categoria;
import com.javierbarciela.proyectofin.modelo.Producto;
import com.javierbarciela.proyectofin.modelo.Usuario;
import com.javierbarciela.proyectofin.service.ProyectoFinService;
import com.javierbarciela.proyectofin.util.CellEditor;
import com.javierbarciela.proyectofin.util.Foto;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JTable;
import javax.swing.JTree;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeCellRenderer;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author pc
 */
public class VerProductosEnVenta extends javax.swing.JFrame {

    private Foto foto = new Foto();
    private ProyectoFinService service = new ProyectoFinService();
    private CellEditor cellEditor = new CellEditor();
    private DefaultMutableTreeNode trRaiz;
    private Usuario usuario;
    
    private List<Integer> filas = new ArrayList<>(); 
        
    private boolean editable = false;
    
    public VerProductosEnVenta(Usuario u) {
        this.usuario = u;
        
        initComponents();
        crearArbolCategorias();
        treCategorias.setCellRenderer(new CategoriasRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        treCategorias = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ver Productos En Venta");
        jPanel3.add(jLabel1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jPanel1.add(btnComprar);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        treCategorias.setModel(null);
        treCategorias.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treCategoriasValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(treCategorias);

        jSplitPane1.setLeftComponent(jScrollPane3);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Valoración", "Vendedor", "Cantidad", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setRowHeight(40);
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(735, 512));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void treCategoriasValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treCategoriasValueChanged
        TreePath path = evt.getPath();
        if (path.getPathCount() == 2) {
            DefaultMutableTreeNode treCategorias = (DefaultMutableTreeNode) path.getLastPathComponent();
            Categoria c = (Categoria) treCategorias.getUserObject();
            cargarProductosCategoria(c);
        }
    }//GEN-LAST:event_treCategoriasValueChanged
    
    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        if(tblProductos.getSelectedColumn() == 2 || tblProductos.getSelectedColumn() == 5) {
            editable = true;
        } else {
            editable = false;
        } 
    }//GEN-LAST:event_tblProductosMouseClicked
    
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new Principal(this.usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        String a = "a ver qué pasa";
    }//GEN-LAST:event_btnComprarActionPerformed

    private void crearArbolCategorias(){
        trRaiz = new DefaultMutableTreeNode("Categorías");
        for (Categoria c : service.getCategorias()){
            DefaultMutableTreeNode trCat = new DefaultMutableTreeNode(c);
            trRaiz.add(trCat);
        }
        TreeModel model = new DefaultTreeModel(trRaiz);
        treCategorias.setModel(model);
    }
    
  
    
    class CategoriasRenderer implements TreeCellRenderer{

        @Override
        public Component getTreeCellRendererComponent(JTree tree, Object value, boolean selected, boolean expanded, boolean leaf, int row, boolean hasFocus) {
            JLabel lbl = new JLabel();
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) value;
            if (row == 0){
                lbl.setText("Categoría");
                Icon ic = IconFontSwing.buildIcon(FontAwesome.ADDRESS_BOOK, 20);
                lbl.setIcon(ic);
            } else {
                lbl.setText(nodo.getUserObject().toString());
                if (nodo.getUserObject() instanceof Categoria) {
                    Categoria c = (Categoria) nodo.getUserObject();
                    switch (c.getIdCategoria()) {
                        case 1:
                            ImageIcon ic = foto.establecerFotoCategoriaFactor(c,20.0);
                            lbl.setIcon(ic);
                            break;
                        case 2:
                            ic = foto.establecerFotoCategoriaFactor(c,20.0);
                            lbl.setIcon(ic);
                            break;
                        case 3:
                            ic = foto.establecerFotoCategoriaFactor(c,20.0);
                            lbl.setIcon(ic);
                            break;
                        default:
                            ic = foto.establecerFotoCategoriaFactor(c,20.0);
                            lbl.setIcon(ic);
                            break;
                    }
                }
            }
            return lbl;
        }
    }
    
    
    
    private void cargarProductosCategoria(Categoria c) {
        String[] titulos = {"Nombre", "Precio", "Valoración", "Vendedor", "Cantidad", "Stock"};
        List<Producto> productos = service.getProductosCategoria(c);
        Object[][] datos = new Object[productos.size()][6] ;
        for(int i=0; i<productos.size(); i++){
            /*datos[i][0] = false;*/
            datos[i][0] = productos.get(i).getNombre();
            datos[i][1] = String.valueOf(productos.get(i).getPrecio()) + "€";
            datos[i][2] = String.valueOf(productos.get(i).getValoracion());
            datos[i][3] = service.getUsuario(productos.get(i).getIdUsuario()).getNombre();
            datos[i][4] = "0";
            String stock = "";
            if (productos.get(i).getCantidad() > 0){
                stock = "En stock";
            } else {
                stock = "Sin stock";
            }
            datos[i][5] = stock;  
        }
        
        /*
        DefaultTableModel model = new DefaultTableModel(){
            public Class<?> getColumnClass(int column){
                switch (column){
                    case 0:
                        return column == 0 ? Boolean.class : super.getColumnClass(column);
                    case 1:
                        return column == 1 ? String.class : super.getColumnClass(column);
                    case 2:
                        return column == 2 ? JFormattedTextField.class : super.getColumnClass(column);
                    case 3:
                        return column == 3 ? JSlider.class : super.getColumnClass(column);
                    case 4:
                        return column == 4 ? Boolean.class : super.getColumnClass(column);
                    default:
                        return column == 5 ? JFormattedTextField.class : super.getColumnClass(column);
                }
            }
        };
        tblProductos.setModel(model);
        
        model.addColumn("Seleccionar");
        model.addColumn("Nombre");
        model.addColumn("Precio");
        model.addColumn("Valoración");
        model.addColumn("Vendedor");
        model.addColumn("Cantidad");
        model.addColumn("Stock");
        
        for(int i=0;i<productos.size();i++){
            model.addRow(new Object[0]);
            model.setValueAt(false,i,0);
            model.setValueAt("Our Row"+(i+1),i,1);
            model.setValueAt("Our Row"+(i+1),i,2);
            model.setValueAt("Our Row"+(i+1),i,3);
            model.setValueAt("Our Row"+(i+1),i,4);
            model.setValueAt("Our Row"+(i+1),i,5);
            model.setValueAt("Our Row"+(i+1),i,6);
        }*/
        
        
        DefaultTableModel modelo = new DefaultTableModel(datos, titulos){
        public boolean isCellEditable(int row, int column){
            switch(column){
                    case 4:
                        return true;
                    default:
                        return false;
            }
        }};
        tblProductos.setModel(modelo);
        
        
        /*
        tblProductos.getColumnModel().getColumn(0)
                .setCellRenderer(new TableCellRenderer() {
                    @Override
                    public Component getTableCellRendererComponent(
                            JTable table,
                            Object value,
                            boolean isSelected,
                            boolean hasFocus,
                            int row,
                            int column) {
                        boolean  pr = new Boolean(value.toString());
                        JCheckBox cb = new JCheckBox();
                        cb.setSelected(pr);
                        return cb;
                    }
                });*/
        tblProductos.getColumnModel().getColumn(1)
                .setCellRenderer(new TableCellRenderer() {
                    @Override
                    public Component getTableCellRendererComponent(
                            JTable table,
                            Object value,
                            boolean isSelected,
                            boolean hasFocus,
                            int row,
                            int column) {
                        JFormattedTextField ftx = new JFormattedTextField(value);
                        
                        return ftx;
                    }
                });
        tblProductos.getColumnModel().getColumn(2)
                .setCellRenderer(new TableCellRenderer() {
                    @Override
                    public Component getTableCellRendererComponent(
                            JTable table,
                            Object value,
                            boolean isSelected,
                            boolean hasFocus,
                            int row,
                            int column) {
                        JSlider js = new JSlider(1, 5, Integer.parseInt(String.valueOf(value)));
                        
                        return js;
                    }
                });
        tblProductos.getColumnModel().getColumn(4)
                .setCellRenderer(new TableCellRenderer() {
                    @Override
                    public Component getTableCellRendererComponent(
                            JTable table,
                            Object value,
                            boolean isSelected,
                            boolean hasFocus,
                            int row,
                            int column) {
                        JFormattedTextField ftx = new JFormattedTextField(value);
                        
                        return ftx;
                    }
                });
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTree treCategorias;
    // End of variables declaration//GEN-END:variables
}
